### ISSUE TITLE
Can't bind to 'min' since it isn't a known property of 'ion-range-slider'.

### ISSUE THREAD

**Issue by GoHaddi** [IonDen/ion.rangeSlider#496]
Hi

I tried to use the demo as shown but it does not seem to work, please help!
I changed nothing and i still get this:

> ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'min' since it isn't a known property of 'ion-range-slider'.
1. If 'ion-range-slider' is an Angular component and it has 'min' input, then verify that it is part of this module.
2. If 'ion-range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ion-range-slider #sliderElement
                          type="double"
                          [ERROR ->][min]="myMinVar"
                          max="100"
                          from="28"
"): ng:///MainViewerModule/PlayControlPanel.html@20:26
'ion-range-slider' is not a known element:
1. If 'ion-range-slider' is an Angular component, then verify that it is part of this module.
2. If 'ion-range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
            </div>
        </div>
        [ERROR ->]<ion-range-slider #sliderElement
                          type="double"
                          "): ng:///MainViewerModule/PlayControlPanel.html@18:8
Error: Template parse errors:
Can't bind to 'min' since it isn't a known property of 'ion-range-slider'.
1. If 'ion-range-slider' is an Angular component and it has 'min' input, then verify that it is part of this module.
2. If 'ion-range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ion-range-slider #sliderElement
                          type="double"
                          [ERROR ->][min]="myMinVar"
                          max="100"
                          from="28"
"): ng:///MainViewerModule/PlayControlPanel.html@20:26
'ion-range-slider' is not a known element:
1. If 'ion-range-slider' is an Angular component, then verify that it is part of this module.
2. If 'ion-range-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
            </div>
        </div>
        [ERROR ->]<ion-range-slider #sliderElement
                          type="double"
                          "): ng:///MainViewerModule/PlayControlPanel.html@18:8
    at syntaxError (http://localhost:8300/vendor.bundle.js:87259:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:8300/vendor.bundle.js:98379:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:8300/vendor.bundle.js:112531:39)
    at http://localhost:8300/vendor.bundle.js:112451:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:8300/vendor.bundle.js:112451:19)
    at http://localhost:8300/vendor.bundle.js:112338:19
    at Object.then (http://localhost:8300/vendor.bundle.js:87248:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:8300/vendor.bundle.js:112337:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:8300/vendor.bundle.js:112266:37)
    at syntaxError (http://localhost:8300/vendor.bundle.js:87259:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:8300/vendor.bundle.js:98379:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:8300/vendor.bundle.js:112531:39)
    at http://localhost:8300/vendor.bundle.js:112451:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:8300/vendor.bundle.js:112451:19)
    at http://localhost:8300/vendor.bundle.js:112338:19
    at Object.then (http://localhost:8300/vendor.bundle.js:87248:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:8300/vendor.bundle.js:112337:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:8300/vendor.bundle.js:112266:37)
    at resolvePromise (http://localhost:8300/polyfills.bundle.js:3322:31)
    at resolvePromise (http://localhost:8300/polyfills.bundle.js:3293:17)
    at http://localhost:8300/polyfills.bundle.js:3370:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8300/polyfills.bundle.js:2963:31)
    at Object.onInvokeTask (http://localhost:8300/vendor.bundle.js:117298:33)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8300/polyfills.bundle.js:2962:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:8300/polyfills.bundle.js:2730:47)
    at drainMicroTaskQueue (http://localhost:8300/polyfills.bundle.js:3134:35)
    at <anonymous>
defaultErrorLogger @ core.es5.js:1020

>

**Comment by IonDen** [comment]
Hello. ion.RangeSlider does not have min property. It has data-min and data-max (same for others - data-from, data-to, etc.)

Also it have value attribute, which gets from and to params.

**Comment by lazycodie** [comment]
Does anybody overcome by this issue?if yes please help me rectify the error?
